define({
    "_HEADER_STATE":"推介",
    "_SHOW":"表现",
    "_START_PRICE":"推股价",
    "_TARGET_PRICE":"目标价",
    "_STOP_PRICE":"止损价",
    "_AVG_PRICE":"平均价",
    "_CALLING_BUY":"跟买",
    "_CALLING_LOST":"跟输",
    "_CALLING_PROFIT":"跟赢",
    "_SHOP_LOSS":"止损",
    "_SHOP_PROFIT":"止贏",
    "_CALLING":"继续跟",
    "_PUSH_DATE":"推股日"
});