define({
    "_HEADER_STATE":"推介",
    "_SHOW":"表現",
    "_START_PRICE":"推股價",
    "_TARGET_PRICE":"目標價",
    "_STOP_PRICE":"止蝕價",
    "_AVG_PRICE":"平均價",
    "_CALLING_BUY":"跟買",
    "_CALLING_LOST":"跟输",
    "_CALLING_PROFIT":"跟赢",
    "_SHOP_LOSS":"止损",
    "_SHOP_PROFIT":"止贏",
    "_CALLING":"繼續跟",
    "_PUSH_DATE":"推股日"
})